### ISSUE TITLE
Developer sync: Call to a member function toLink() on boolean

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#249]
**Describe the bug**
Not sure about the requirements yet to reproduce this bug but the following PHP error could occur while the developer sync is running:

```
 [error]  Error: Call to a member function toLink() on boolean in Drupal\apigee_edge\Job\DeveloperCreateUpdate->executeRequest() (line 78 of web/modules/contrib/apigee_edge/src/Job/DeveloperCreateUpdate.php) #0 web/modules/contrib/apigee_edge/src/Job/EdgeJob.php(47): Drupal\apigee_edge\Job\DeveloperCreateUpdate->executeRequest()
#1 web/modules/contrib/apigee_edge/src/JobExecutor.php(150): Drupal\apigee_edge\Job\EdgeJob->execute()
#2 web/modules/contrib/apigee_edge/src/Controller/DeveloperSyncController.php(196): Drupal\apigee_edge\JobExecutor->call(Object(Drupal\apigee_edge\Job\DeveloperUpdate))
#3 [internal function]: Drupal\apigee_edge\Controller\DeveloperSyncController::batchExecuteJobs('developer_sync_...', Array)
#4 web/modules/contrib/apigee_edge/src/CliService.php(44): call_user_func_array(Array, Array)
#5 web/modules/contrib/apigee_edge/src/Commands/ApigeeEdgeCommands.php(57): Drupal\apigee_edge\CliService->sync(Object(Drush\Style\DrushStyle), 'dt')
#6 [internal function]: Drupal\apigee_edge\Commands\ApigeeEdgeCommands->sync(Array)
#7 vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#8 vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#9 vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#18 vendor/drush/drush/drush(4): require('/var/www/develo...')
#19 {main}. 
```

**Version Info**
1.0

**Comment by cnovak** [comment]
This issue is pretty old, let's try to replicate and if we cannot we can close it out.

**Comment by phdhiren** [comment]
@mxr576 , I could not replicate the issue. Is there any specific condition where the developer sync is throwing an error?

**Comment by raakesh-blokhra** [comment]
Unable to replicate. Let's close this issue. We will reopen if reproduced.
