### ISSUE TITLE
Error while configuring OAuth for SAML enabled Orgs

### ISSUE THREAD

**Issue by satyapappu** [apigee/apigee-edge-drupal#30]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        |yes
| New Feature?                | no
| Module Version              | 1.0.0-alpha3
| PHP Client version          | 2.0.0-alpha2
| Requires PHP client fix     | don't know

#### Actual Behavior
Trying to configure Edge module to connect to a SAML enabled organization. Documentation only explains Basic Auth. (https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge). We have set up a new OAuth (SAML) key using the devadmin credentials, key and secret. We then created to set up a new OAuth (SAML) token key of key type "Apigee Edge OAUTh token with "Key Provider" of "Private File".  There were not values under "value".  When clicking "Save" we saw a few errors and warnings from Drupal about not being able to handle request, as shown below - 

``` 
Warning: Illegal string offset 'submitted' in Drupal\key\Form\KeyFormBase->validateForm() (line 252 of /app/web/modules/contrib/key/src/Form/KeyFormBase.php) #0 /app/web/core/includes/bootstrap.inc(582): _drupal_error_handler_real(2, 'Illegal string ...', '/app/web/module...', 252, Array) #1 /app/web/modules/contrib/key/src/Form/KeyFormBase.php(252): _drupal_error_handler(2, 'Illegal string ...', '/app/web/module...', 252, Array) #2 [internal function]: Drupal\key\Form\KeyFormBase->validateForm(Array, Object(Drupal\Core\Form\FormState)) #3 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(83): call_user_func_array(Array, Array) #4 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(276): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) #5 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(119): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'key_add_form') #6 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(575): Drupal\Core\Form\FormValidator->validateForm('key_add_form', Array, Object(Drupal\Core\Form\FormState)) #7 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(318): Drupal\Core\Form\FormBuilder->processForm('key_add_form', Array, Object(Drupal\Core\Form\FormState)) #8 /app/web/core/lib/Drupal/Core/Controller/FormController.php(74): Drupal\Core\Form\FormBuilder->buildForm('key_add_form', Object(Drupal\Core\Form\FormState)) #9 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #10 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #11 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #12 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #13 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #14 /app/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #16 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /app/web/core/lib/Drupal/Core/DrupalKernel.php(666): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #25 {main}.
```

```
Notice: Uninitialized string offset: 0 in Drupal\key\Form\KeyFormBase->validateForm() (line 252 of /app/web/modules/contrib/key/src/Form/KeyFormBase.php) #0 /app/web/core/includes/bootstrap.inc(582): _drupal_error_handler_real(8, 'Uninitialized s...', '/app/web/module...', 252, Array) #1 /app/web/modules/contrib/key/src/Form/KeyFormBase.php(252): _drupal_error_handler(8, 'Uninitialized s...', '/app/web/module...', 252, Array) #2 [internal function]: Drupal\key\Form\KeyFormBase->validateForm(Array, Object(Drupal\Core\Form\FormState)) #3 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(83): call_user_func_array(Array, Array) #4 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(276): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) #5 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(119): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'key_add_form') #6 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(575): Drupal\Core\Form\FormValidator->validateForm('key_add_form', Array, Object(Drupal\Core\Form\FormState)) #7 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(318): Drupal\Core\Form\FormBuilder->processForm('key_add_form', Array, Object(Drupal\Core\Form\FormState)) #8 /app/web/core/lib/Drupal/Core/Controller/FormController.php(74): Drupal\Core\Form\FormBuilder->buildForm('key_add_form', Object(Drupal\Core\Form\FormState)) #9 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #10 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #11 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #12 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #13 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #14 /app/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #16 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /app/web/core/lib/Drupal/Core/DrupalKernel.php(666): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #25 {main}.
```
However, we were able to add both key and token key for OAuth the second time without problem.

#### Proposed Solution
Need documentation for SAML/OAuth configuration, and fix whatever errors we saw above.

**Comment by cnovak** [comment]
FYI I helped @satyapappu with entering this ticket.  Docs is working on the OAuth info and should it up soon.  Will keep you posted @satyapappu

**Comment by peterserfozo** [comment]
We've fixed a bug in the key module, the next module release will contain the necessary patch:
https://github.com/apigee/apigee-edge-drupal/pull/33
Key module patch:
https://www.drupal.org/project/key/issues/2982124

**Comment by cnovak** [comment]
Thanks @peterserfozo.  @satyapappu here are instructions on how to apply the patch until it is added to the Key module or until this module adds the patch in the next release:

1. Go to the root of your Drupal project and run `composer require cweagans/composer-patches` to add composer-patches  to your "drupal-composer/drupal-project" composer.json file.
2. Open up the "drupal-composer/drupal-project" composer.json file and add the following into the "extra" section:
```
"patches": {
  "drupal/key": {
    "Fix for Apigee Edge OAuth https://github.com/apigee/apigee-edge-drupal/issues/30": "https://www.drupal.org/files/issues/2018-06-27/key-fix-implementation-of-nonekeyinput-2982124-2.patch"
  }
}
```
3. Run `composer remove drupal/apigee_edge`
4. Run `composer remove drupal/key`
5. Run `composer require drupal/apigee_edge`

**Comment by mxr576** [comment]
I do not think that it is necessary to remove apigee_edge or the key module after you added the patch to the composer.json. Simple `composer update none` or `composer update drupal/key` should be enough to tell Composer to remove the current key module version and download it again and patch it.

**Comment by cnovak** [comment]
Agree @mxr576, thought that would work.  However,  running `composer update drupal/key` did not add the patch.  @satyapappu try @mxr576 suggestion and let us know if that works instead of my instructions.

**Comment by mxr576** [comment]
We fixed this issue in a call so I am closing this issue.
